# See: https://upptime.js.org/docs/configuration
owner: carbon-design-system
repo: uptime

sites:
  - name: Carbon Design System
    url: https://www.carbondesignsystem.com
  - name: Carbon React Storybook
    url: https://react.carbondesignsystem.com
  - name: Carbon Charts Storybook
    url: https://charts.carbondesignsystem.com
  - name: Carbon for IBM.com
    url: https://www.ibm.com/standards/carbon
  - name: Carbon for IBM.com Web Components Storybook
    url: https://www.ibm.com/standards/carbon/web-components
  - name: Carbon for IBM.com React Storybook
    url: https://www.ibm.com/standards/carbon/react
  - name: Carbon Web Components Storybook
    url: https://web-components.carbondesignsystem.com
  - name: Fake Site Testing
    url: https://not-a-real-site.carbondesignsystem.com

status-website:
  baseUrl: /uptime
  name: Carbon Uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
